version: '3.4'

services:
  db:
    image: postgres:11.5-alpine
    environment: &db_environment
      POSTGRES_DB: developerportal
      POSTGRES_HOST: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test-password
    expose:
      - 5432

  app:
    depends_on:
      - db
    image: mdnwebdocs/developer-portal:latest
    environment:
      <<: *db_environment
      BASE_URL: http://localhost:8000
      DJANGO_ENV: dev
      DJANGO_SECRET_KEY: test-key
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./media:/app/media
