---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stage-full-access
  namespace: dev-portal-stage
rules:
- apiGroups: [""]
  resources:
    - namespaces
  verbs:
    - get
    - list
    - watch
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prod-full-access
  namespace: dev-portal-prod
rules:
- apiGroups: [""]
  resources:
    - namespaces
  verbs:
    - get
    - list
    - watch
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-prod-access
  namespace: dev-portal-prod
subjects:
- kind: Group
  name: "jenkins-access"
  namespace: dev-portal-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prod-full-access

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-stage-access
  namespace: dev-portal-stage
subjects:
- kind: Group
  name: "jenkins-access"
  namespace: dev-portal-stage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stage-full-access
